packages:
  - src/*
catalog:
  "@eslint/js": 9.17.0
  "@mantine/core": 7.16.0
  "@fortawesome/fontawesome-svg-core": 6.7.2
  "@fortawesome/free-solid-svg-icons": 6.7.2
  "@fortawesome/react-fontawesome": 0.2.2
  "@tanstack/react-query": 5.64.1
  "@trivago/prettier-plugin-sort-imports": 5.2.1
  "@types/react": 19.0.7
  "@types/react-dom": 19.0.3
  "@vitejs/plugin-react": 4.3.4
  dompurify: 3.2.3
  eslint: 9.17.0
  eslint-plugin-react-hooks: 5.0.0
  eslint-plugin-react-refresh: 0.4.16
  globals: 15.14.0
  prettier: 3.4.2
  react: 19.0.0
  react-dom: 19.0.0
  react-router-dom: 7.1.1
  typescript: 5.6.2
  typescript-eslint: 8.18.2
  vite: 6.0.5