packages:
  - src/*
catalog:
  "@eslint/js": 9.32.0
  "@mantine/core": 8.2.4
  "@fortawesome/fontawesome-svg-core": 7.0.0
  "@fortawesome/free-solid-svg-icons": 7.0.0
  "@fortawesome/react-fontawesome": 0.2.3
  "@tanstack/react-query": 5.84.2
  "@trivago/prettier-plugin-sort-imports": 5.2.2
  "@types/react": 19.1.9
  "@types/react-dom": 19.1.7
  "@vitejs/plugin-react": 5.0.0
  dompurify: 3.2.6
  eslint: 9.32.0
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.20
  globals: 16.3.0
  html-entities: 2.6.0
  prettier: 3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  react-router-dom: 7.8.0
  typescript: 5.9.2
  typescript-eslint: 8.39.0
  uuid: 11.1.0
  vite: 7.1.1