packages:
  - src/*
catalog:
  "@eslint/js": 9.24.0
  "@mantine/core": 7.17.4
  "@fortawesome/fontawesome-svg-core": 6.7.2
  "@fortawesome/free-solid-svg-icons": 6.7.2
  "@fortawesome/react-fontawesome": 0.2.2
  "@tanstack/react-query": 5.73.3
  "@trivago/prettier-plugin-sort-imports": 5.2.2
  "@types/react": 19.1.1
  "@types/react-dom": 19.1.2
  "@vitejs/plugin-react": 4.3.4
  dompurify: 3.2.5
  eslint: 9.24.0
  eslint-plugin-react-hooks: 5.0.0
  eslint-plugin-react-refresh: 0.4.19
  globals: 16.0.0
  html-entities: 2.6.0
  prettier: 3.5.3
  react: 19.1.0
  react-dom: 19.1.0
  react-router-dom: 7.5.0
  typescript: 5.8.3
  typescript-eslint: 8.29.1
  uuid: 11.1.0
  vite: 6.2.6